Modify publish.yml for testing
Test if yarn commands for setting up the release work with node 18.x

Signed-off-by: Gabriela Gutierrez <gabigutierrez@google.com>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,9 +1,10 @@
-name: Publish
-run-name: Publish new version on ${{ github.ref_name }}, triggered by ${{ github.triggering_actor }}
+name: (Test) Publish
+run-name: (Test) Publish new version on ${{ github.ref_name }}, triggered by ${{ github.triggering_actor }}
 
 on:
   push:
     branches:
+      - test-gabi
       - latest-release
       - next-release
 
@@ -77,8 +78,8 @@ jobs:
           yarn release:version --apply --verbose
           cd ..
 
-          git config --global user.name "storybook-bot"
-          git config --global user.email "32066757+storybook-bot@users.noreply.github.com"
+          git config --global user.name "Gabriela Gutierrez"
+          git config --global user.email "gabigutierrez@google.com"
           git add .
           git commit -m "Bump version from $CURRENT_VERSION to $DEFERRED_NEXT_VERSION [skip ci]" || true
           git push origin ${{ github.ref_name }}
@@ -101,89 +102,89 @@ jobs:
         working-directory: .
         run: yarn task --task=install --start-from=install
 
-      - name: Publish
-        if: steps.publish-needed.outputs.published == 'false'
-        env:
-          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-        run: yarn release:publish --tag ${{ steps.is-prerelease.outputs.prerelease == 'true' && 'next' || 'latest' }} --verbose
+      # - name: Publish
+      #   if: steps.publish-needed.outputs.published == 'false'
+      #   env:
+      #     YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+      #   run: yarn release:publish --tag ${{ steps.is-prerelease.outputs.prerelease == 'true' && 'next' || 'latest' }} --verbose
 
-      - name: Get target branch
-        id: target
-        run: echo "target=${{ github.ref_name == 'next-release' && 'next' || 'main' }}" >> $GITHUB_OUTPUT
+      # - name: Get target branch
+      #   id: target
+      #   run: echo "target=${{ github.ref_name == 'next-release' && 'next' || 'main' }}" >> $GITHUB_OUTPUT
 
-      - name: Get changelog for ${{ steps.version.outputs.current-version }}
-        if: steps.publish-needed.outputs.published == 'false'
-        id: changelog
-        run: yarn release:get-changelog-from-file ${{ steps.version.outputs.current-version }}
+      # - name: Get changelog for ${{ steps.version.outputs.current-version }}
+      #   if: steps.publish-needed.outputs.published == 'false'
+      #   id: changelog
+      #   run: yarn release:get-changelog-from-file ${{ steps.version.outputs.current-version }}
 
-      # tags are needed to get list of patches to label as picked
-      - name: Fetch git tags
-        if: github.ref_name == 'latest-release'
-        run: git fetch --tags origin
+      # # tags are needed to get list of patches to label as picked
+      # - name: Fetch git tags
+      #   if: github.ref_name == 'latest-release'
+      #   run: git fetch --tags origin
 
-      # when this is a patch release from main, label any patch PRs included in the release
-      # when this is a stable release from next, label ALL patch PRs found, as they will per definition be "patched" now
-      - name: Label patch PRs as picked
-        if: github.ref_name == 'latest-release' || (steps.publish-needed.outputs.published == 'false' && steps.target.outputs.target == 'next' && !steps.is-prerelease.outputs.prerelease)
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: yarn release:label-patches ${{ steps.target.outputs.target == 'next' && '--all' || '' }}
+      # # when this is a patch release from main, label any patch PRs included in the release
+      # # when this is a stable release from next, label ALL patch PRs found, as they will per definition be "patched" now
+      # - name: Label patch PRs as picked
+      #   if: github.ref_name == 'latest-release' || (steps.publish-needed.outputs.published == 'false' && steps.target.outputs.target == 'next' && !steps.is-prerelease.outputs.prerelease)
+      #   env:
+      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: yarn release:label-patches ${{ steps.target.outputs.target == 'next' && '--all' || '' }}
 
-      - name: Create GitHub Release
-        if: steps.publish-needed.outputs.published == 'false'
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release create \
-          v${{ steps.version.outputs.current-version }} \
-            --repo "${{ github.repository }}" \
-            --target ${{ github.ref_name }} \
-            --title "v${{ steps.version.outputs.current-version }}" \
-            --notes "${{ steps.changelog.outputs.changelog }}" \
-            ${{ steps.is-prerelease.outputs.prerelease == 'true' && '--prerelease' || '' }}
+      # - name: Create GitHub Release
+      #   if: steps.publish-needed.outputs.published == 'false'
+      #   env:
+      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #     gh release create \
+      #     v${{ steps.version.outputs.current-version }} \
+      #       --repo "${{ github.repository }}" \
+      #       --target ${{ github.ref_name }} \
+      #       --title "v${{ steps.version.outputs.current-version }}" \
+      #       --notes "${{ steps.changelog.outputs.changelog }}" \
+      #       ${{ steps.is-prerelease.outputs.prerelease == 'true' && '--prerelease' || '' }}
 
-      - name: Merge ${{ github.ref_name }} into ${{ steps.target.outputs.target }}
-        run: |
-          git config --global user.name "storybook-bot"
-          git config --global user.email "32066757+storybook-bot@users.noreply.github.com"
-          git fetch origin ${{ steps.target.outputs.target }}
-          git checkout ${{ steps.target.outputs.target }}
-          git merge ${{ github.ref_name }}
-          git push origin ${{ steps.target.outputs.target }}
+      # - name: Merge ${{ github.ref_name }} into ${{ steps.target.outputs.target }}
+      #   run: |
+      #     git config --global user.name "storybook-bot"
+      #     git config --global user.email "32066757+storybook-bot@users.noreply.github.com"
+      #     git fetch origin ${{ steps.target.outputs.target }}
+      #     git checkout ${{ steps.target.outputs.target }}
+      #     git merge ${{ github.ref_name }}
+      #     git push origin ${{ steps.target.outputs.target }}
 
-      - name: Sync CHANGELOG.md from `main` to `next`
-        if: github.ref_name == 'latest-release'
-        working-directory: .
-        run: |
-          git fetch origin next
-          git checkout next
-          git pull
-          git checkout origin/main ./CHANGELOG.md
-          git add ./CHANGELOG.md
-          git commit -m "Update CHANGELOG.md for v${{ steps.version.outputs.current-version }} [skip ci]"
-          git push origin next
+      # - name: Sync CHANGELOG.md from `main` to `next`
+      #   if: github.ref_name == 'latest-release'
+      #   working-directory: .
+      #   run: |
+      #     git fetch origin next
+      #     git checkout next
+      #     git pull
+      #     git checkout origin/main ./CHANGELOG.md
+      #     git add ./CHANGELOG.md
+      #     git commit -m "Update CHANGELOG.md for v${{ steps.version.outputs.current-version }} [skip ci]"
+      #     git push origin next
 
-      - name: Sync version JSONs from `next-release` to `main`
-        if: github.ref_name == 'next-release'
-        working-directory: .
-        run: |
-          VERSION_FILE="./docs/versions/${{ steps.is-prerelease.outputs.prerelease == 'true' && 'next' || 'latest' }}.json"
-          git fetch origin main
-          git checkout main
-          git pull
-          git checkout origin/next-release $VERSION_FILE
-          git add $VERSION_FILE
-          git commit -m "Update $VERSION_FILE for v${{ steps.version.outputs.current-version }}"
-          git push origin main
+      # - name: Sync version JSONs from `next-release` to `main`
+      #   if: github.ref_name == 'next-release'
+      #   working-directory: .
+      #   run: |
+      #     VERSION_FILE="./docs/versions/${{ steps.is-prerelease.outputs.prerelease == 'true' && 'next' || 'latest' }}.json"
+      #     git fetch origin main
+      #     git checkout main
+      #     git pull
+      #     git checkout origin/next-release $VERSION_FILE
+      #     git add $VERSION_FILE
+      #     git commit -m "Update $VERSION_FILE for v${{ steps.version.outputs.current-version }}"
+      #     git push origin main
 
-      - name: Overwrite main with next
-        if: steps.target.outputs.target == 'next' && steps.is-prerelease.outputs.prerelease == 'false'
-        run: git push --force origin next:main
+      # - name: Overwrite main with next
+      #   if: steps.target.outputs.target == 'next' && steps.is-prerelease.outputs.prerelease == 'false'
+      #   run: git push --force origin next:main
 
-      - name: Report job failure to Discord
-        if: failure()
-        env:
-          DISCORD_WEBHOOK: ${{ secrets.DISCORD_MONITORING_URL }}
-        uses: Ilshidur/action-discord@master
-        with:
+      # - name: Report job failure to Discord
+      #   if: failure()
+      #   env:
+      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_MONITORING_URL }}
+      #   uses: Ilshidur/action-discord@master
+      #   with:
           args: 'The GitHub Action for publishing version ${{ steps.version.outputs.current-version }} (triggered by ${{ github.triggering_actor }}) failed! See run at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
